### ISSUE TITLE
密码问题

### ISSUE THREAD

**Issue by Edison199902222** [hardik0/Multi-Object-Tracking-Google-Colab#1]
老哥 请问from google.colab import drive
drive.mount('/content/gdrive') 这个的密码是多少啊

**Comment by hardik0** [comment]
Hey @Edison199902222 ,
If you’re new to Google Colab, check this [Colab intro ](https://colab.research.google.com/notebooks/intro.ipynb) for basic and [Google drive IO](https://colab.research.google.com/notebooks/io.ipynb) for mount drive
